#pragma once

// #include <AP_Airspeed/AP_Airspeed_config.h>
// #include <AP_RPM/AP_RPM_config.h>

#ifndef AP_STEPPERDRIVER_ENABLED
#define AP_STEPPERDRIVER_ENABLED 1
#endif

#ifndef AP_STEPPERDRIVER_BACKEND_DEFAULT_ENABLED
#define AP_STEPPERDRIVER_BACKEND_DEFAULT_ENABLED AP_STEPPERDRIVER_ENABLED
#endif

#ifndef AP_STEPPERDRIVER_DRV8462SPI_ENABLED
#define HAL_STR_DRV8462_NAME "drv8462"
#define AP_STEPPERDRIVER_DRV8462SPI_ENABLED AP_STEPPERDRIVER_BACKEND_DEFAULT_ENABLED
#endif


