#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#include <AP_Airspeed/AP_Airspeed_config.h>
#include <AP_RPM/AP_RPM_config.h>

#ifndef AP_GENERICENCODER_ENABLED
#define AP_GENERICENCODER_ENABLED 1
#endif

#ifndef AP_GENERICENCODER_BACKEND_DEFAULT_ENABLED
#define AP_GENERICENCODER_BACKEND_DEFAULT_ENABLED AP_GENERICENCODER_ENABLED
#endif

#ifndef AP_GENERICENCODER_AS5600I2C_ENABLED
#define AP_GENERICENCODER_AS5600I2C_ENABLED AP_GENERICENCODER_BACKEND_DEFAULT_ENABLED
#endif
