#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_STEERINGENCODER_ENABLED
#define AP_STEERINGENCODER_ENABLED 1
#endif

#ifndef AP_STEERINGENCODER_BACKEND_DEFAULT_ENABLED
#define AP_STEERINGENCODER_BACKEND_DEFAULT_ENABLED AP_STEERINGENCODER_ENABLED
#endif

#ifndef AP_STEERINGENCODER_AS5600I2C_ENABLED
#define AP_STEERINGENCODER_AS5600I2C_ENABLED AP_STEERINGENCODER_BACKEND_DEFAULT_ENABLED
#endif
